### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by voidrohit**

### CODE REVIEW

**Review by swetadash0610 — CHANGES_REQUESTED** [review]
The news API works fine. But some minor changes are required before merging it.
1. The size of all news cards should be of the same height.
2. "Read more" button should redirect to open in a new tab

Let us know after the mentioned changes are done.

**Review by swagat-das — CHANGES_REQUESTED** [review]
You must work on news API placing it below the club initiatives part in the index.html page and should be responsive also.

**Comment by voidrohit** [comment]
Done it.

**Comment by swetadash0610** [comment]
@voidrohit Good work! Your PR has been merged. Just write a little more descriptive commit messages from next time.

**Pull request merged**
